# Generated by Django 5.1.7 on 2025-11-14 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('es_votante', models.BooleanField(default=False)),
                ('es_candidato', models.BooleanField(default=False)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoEleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('id_administrador', models.CharField(blank=True, max_length=36, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elecciones.persona'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eventoeleccion')),
                ('persona_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='elecciones.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionEleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ha_votado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eventoeleccion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.persona')),
            ],
            options={
                'unique_together': {('evento', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('propuesta', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eventoeleccion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.persona')),
            ],
            options={
                'unique_together': {('evento', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteo_votos', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eventoeleccion')),
                ('persona_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.persona')),
            ],
            options={
                'unique_together': {('evento', 'persona_candidato')},
            },
        ),
    ]
