# Generated by Django 5.1.7 on 2025-11-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='block_number',
            field=models.BigIntegerField(blank=True, help_text='Block number where commitment was stored', null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='commitment',
            field=models.CharField(blank=True, help_text='Keccak256 hash commitment of the vote', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='onchain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', help_text='Status of blockchain submission', max_length=20),
        ),
        migrations.AddField(
            model_name='voto',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash on blockchain', max_length=66, null=True),
        ),
    ]
