# Generated by Django 5.1.7 on 2025-11-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_voto_block_number_voto_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='persona_votante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='elecciones.persona'),
        ),
    ]
