# Generated by Django 5.1.7 on 2025-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_voto_persona_votante'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='commitment_sender',
            field=models.CharField(blank=True, help_text='Address that submitted the commitment on-chain', max_length=42, null=True),
        ),
    ]
