# Generated by Django 5.1.7 on 2025-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_voto_commitment_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='onchain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('exists', 'Exists'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', help_text='Status of blockchain submission', max_length=20),
        ),
    ]
