# Generated by Django 5.1.7 on 2025-11-21 22:52

import elecciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_alter_voto_onchain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del usuario', null=True, upload_to=elecciones.models.upload_to_usuario),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto_url',
            field=models.CharField(blank=True, help_text='URL externa de foto (deprecado)', max_length=255, null=True),
        ),
    ]
