# Generated by Django 5.1.7 on 2025-11-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_persona_foto_alter_persona_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto_url',
        ),
    ]
